MATOMO_FORCE_UPDATE: false # if matomo image version is > current version the image version will be installed

MATOMO_BACKUP_CRON_EXP: 30 4 * * * #every day at 4:30am
MATOMO_BACKUP_TTL: 15 # Delete backups that are over 15 days

MATOMO_ARCHIVE_CRON_EXP: 5 * * * *

# Apache
MATOMO_SERVER_ADMIN: webmaster@example.org
MATOMO_SERVER_BASE_URL: http://matomo.example.org
MATOMO_SERVER_PATH: /matomo

# Self signed certificat will be generated
# if MATOMO_HTTPS is set to true and no certificat and key are provided.

# To use your custom certificat and key 2 options :
# - add them in service/matomo/assets/apache2/ssl and build the image
# - or during docker run mount a data volume with those files to /container/service/matomo/apache2/ssl
MATOMO_HTTPS: true
MATOMO_HTTPS_CRT_FILENAME: matomo.crt
MATOMO_HTTPS_KEY_FILENAME: matomo.key
MATOMO_HTTPS_CA_CRT_FILENAME: ca.crt

MATOMO_TRUST_PROXY_SSL: false

# LDAP client tls config
MATOMO_LDAP_CLIENT_TLS: false
MATOMO_LDAP_CLIENT_TLS_REQCERT: demand
MATOMO_LDAP_CLIENT_TLS_CA_CRT_FILENAME: ldap-ca.crt
MATOMO_LDAP_CLIENT_TLS_CRT_FILENAME: ldap-client.crt
MATOMO_LDAP_CLIENT_TLS_KEY_FILENAME: ldap-client.key

# MARIADB client tls config
MATOMO_MARIADB_CLIENT_TLS: false
MATOMO_MARIADB_CLIENT_TLS_CA_CRT_FILENAME: database-ca.crt
MATOMO_MARIADB_CLIENT_TLS_CRT_FILENAME: database-client.crt
MATOMO_MARIADB_CLIENT_TLS_KEY_FILENAME: database-client.key

MATOMO_SSL_HELPER_PREFIX: matomo
LDAP_CLIENT_SSL_HELPER_PREFIX: ldap
MARIADB_CLIENT_SSL_HELPER_PREFIX: database

SSL_HELPER_AUTO_RENEW_SERVICES_IMPACTED: :apache2 :php7.0-fpm
