#!/bin/bash -e

# Usage: /sbin/matomo-restore file [file] ...
backupPath="/data/backup"
backupFileSuffix="-matomo.tar.gz"
backupDbSuffix="-matomo-db.tar.gz"
databaseFile="database.sql"

for file in "$@"
do
    echo "Processing file $file"

    if $(echo "$file" | grep -q -e "$backupFileSuffix"); then
        echo "Restore matomo files"
        tar -xvzf $backupPath/$file -C /
        echo "done :)"
    elif $(echo "$file" | grep -q -e "$backupDbSuffix"); then
        echo "Restore matomo database"
        . /container/service/backup/assets/tool/matomo-get-db-params

        rm -rf $databaseFile || true
        tar -xvzf $backupPath/$file

        mysql -u $databaseUser -p$databasePassword --host $host $database < $databaseFile

        rm -rf $databaseFile

        echo "done :)"
    else
      echo "Error: Unknown file type"
    fi
done

exit 0
